name: fall_2025_brain_tumor_diagnosis
channels:
  - conda-forge
dependencies:
  - python = 3.12
  - numpy >=2.1,<3
  - pytorch
  - torchvision
  - torchaudio
  - jupyter
  - matplotlib >= 3.8
  - openpyxl >= 3.0
  - pandas >= 2.0
  - pyarrow
  - scikit-learn >= 1.4
  - sqlalchemy
  - xgboost = 2.1.4
  - pmdarima >= 2.0
  - interpret
  - pandera
  - missingno
  - pygam
  - freetype = 2.13.3
  - nibabel
  - pip >= 24.0
  - pip:
      - cinemagoer
      - lxml
      - pynytimes
      - pyjokes == 0.6.0
      - plotly == 5.24.0
      - seaborn == 0.13.2
      - ucimlrepo